# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nfcore-exoseq-1.0dev
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - conda-forge::openjdk=8.0.144 # Needed for FastQC - conda build hangs without this  - bwa=0.7.17
  - fastqc=0.11.7
  - trim-galore=0.5.0
  - samtools=1.9
  - gatk4=4.0.7.0
  - qualimap=2.2.2a
  - multiqc=1.6
